server:
  port: 9000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

integration:
  stores:
    uri: http://192.168.109.2:8089
    test: '{cipher}316f8cdbb776c23e679bf209014788a6eab7522f48f97114328c2c9388e6b3c1'

stores:
  ribbon:
    ServerListRefreshInterval: 1000

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    hostname: ${CF_INSTANCE_IP:192.168.109.2}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    region: default
    registryFetchIntervalSeconds: 5
    availabilityZones: 
      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

# For demo only allow more hystrix connections
hystrix:
  stream:
    maxConcurrentConnections: 20
    bus:
      enabled: true

spring:
  rabbitmq:
    addresses: amqp://vdiag:vdiag@localhost:5672

logging:
  level:
    com.netflix.discovery: INFO
    # com.netflix.zuul: DEBUG
    # org.springframework.data: DEBUG
    # org.springframework.data.mongodb: DEBUG
    # org.springframework.web: DEBUG
    # org.springframework.boot: INFO
    # org.springframework: INFO

---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
