server:
  port: 8089


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring:
  data:
    mongodb:
      uri: ${vcap.services.${PREFIX:}mongodb.credentials.uri:mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/stores}
  rabbitmq:
    addresses: amqp://vdiag:vdiag@localhost:5672

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    hostname: ${CF_INSTANCE_IP:192.168.109.2}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

logging:
  level:
    com.netflix.discovery: 'OFF'